ens_affiliate_new:
    pattern: /new
    defaults: {_controller: "EnsJobbetBundle:Affiliate:new"}

ens_affiliate_create:
    pattern: /create
    defaults: { _controller: "EnsJobbetBundle:Affiliate:create" }
    requirements: { _method: post }

ens_affiliate_wait:
    pattern: /wait
    defaults: { _controller: "EnsJobeetbundle:Affiliate:wait" }